### ISSUE TITLE
Home page /Draw menu/ Send to address

### ISSUE THREAD

**Issue by Chegemartinx** [Kukuza/tech-prototype#7]
# Acceptance Criteria

# Design

![image](https://user-images.githubusercontent.com/63787845/133285121-58dbe6a4-ba9c-41db-9eda-4fa0b78d282b.png)

Link: https://www.figma.com/file/0fbtX7J7vPDsOX8X87CQc8/Kukuza-and-Wakala-Architecture?node-id=45%3A49

**Comment by steffenkrogmann** [comment]
@Chegemartinx not wrong, but overkill for this prototype. closing this one.
combined these start journey stories in the menu story via acceptance criteria (click starts journey)
